package main

import (
	"sandcard/application"
	"sandcard/controller"
	_ "sandcard/docs" // docs is generated by Swag CLI, you have to import it.
)

// @Title sandcard API reference
// @Description Documentation for HTTP API
// @Contact.name Stepan Morozov
// @Contact.email stepan.morozov.work@gmail.com
func main() {
	var (
		a = application.New()
		c = controller.New(a)
	)
	c.Serve(57428)
}
